# Generated by Django 5.1.1 on 2024-09-10 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailverification_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 9, 59, 5, 807249, tzinfo=datetime.timezone.utc)),
        ),
    ]
