# Generated by Django 5.1.1 on 2024-09-15 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailverification_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 23, 8, 56, 903405, tzinfo=datetime.timezone.utc)),
        ),
    ]
