# Generated by Django 5.1.1 on 2024-11-21 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_emailverification_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 21, 31, 11, 537199, tzinfo=datetime.timezone.utc)),
        ),
    ]
